In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [7]:
df = pd.read_csv(r"C:\Users\user\weather_Navie_bayes_dataset.csv")
df

    Day   Outlook Temperature Humidity    Wind PlayTennis
0     1     Sunny         Hot     High    Weak         No
1     2     Sunny         Hot     High  Strong         No
2     3  Overcast         Hot     High    Weak        Yes
3     4      Rain        Mild     High    Weak        Yes
4     5      Rain        Cool   Normal    Weak        Yes
5     6      Rain        Cool   Normal  Strong         No
6     7  Overcast        Cool   Normal  Strong        Yes
7     8     Sunny        Mild     High    Weak         No
8     9     Sunny        Cool   Normal    Weak        Yes
9    10      Rain        Mild   Normal    Weak        Yes
10   11     Sunny        Mild   Normal  Strong        Yes
11   12  Overcast        Mild     High  Strong        Yes
12   13  Overcast         Hot   Normal    Weak        Yes
13   14      Rain        Mild     High  Strong         No
14   15     Sunny        Cool     High  Strong         No
15   16      Rain         Hot   Normal    Weak        Yes
16   17  Overcast        Cool     High    Weak        Yes
17   18     Sunny        Mild   Normal    Weak        Yes
18   19      Rain        Cool     High    Weak         No
19   20  Overcast        Mild   Normal  Strong        Yes

In [8]:
le= LabelEncoder()
for col in df.columns:
    df[col] = le.fit_transform(df[col])
df

    Day  Outlook  Temperature  Humidity  Wind  PlayTennis
0     0        2            1         0     1           0
1     1        2            1         0     0           0
2     2        0            1         0     1           1
3     3        1            2         0     1           1
4     4        1            0         1     1           1
5     5        1            0         1     0           0
6     6        0            0         1     0           1
7     7        2            2         0     1           0
8     8        2            0         1     1           1
9     9        1            2         1     1           1
10   10        2            2         1     0           1
11   11        0            2         0     0           1
12   12        0            1         1     1           1
13   13        1            2         0     0           0
14   14        2            0         0     0           0
15   15        1            1         1     1           1
16   16        0            0         0     1           1
17   17        2            2         1     1           1
18   18        1            0         0     1           0
19   19        0            2         1     0           1

In [9]:
X = df.drop("PlayTennis", axis=1)
y=df["PlayTennis"]

In [10]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size= 0.2, random_state = 42)

In [ ]:
model = MultinomialNB()
model.fit(X_train,y_train)

In [ ]:
y_pred = model.predict(X_test)
print("Predicted values:", y_pred)

In [ ]:
y_test

In [ ]:
accuracy= accuracy_score(y_test,y_pred)
print("model accuracy:" , accuracy)

In [ ]:
new_weather = pd.DataFrame(
    [[2,0,0,1,1]],
    columns= ["Day","Outlook","Temperature","Humidity","Wind"])
probability = model.predict_proba(new_weather)[0]
probability

In [ ]:
labels= ["No","Yes"]
plt.figure()
plt.bar(labels,probability)
plt.xlabel("Play")
plt.ylabel("Probability")
plt.title("Naives